//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acotma_API.Models_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignacion_Radios
    {
        public int Id_asignacionRadio { get; set; }
        public string usuario { get; set; }
        public Nullable<int> Num_Radio { get; set; }
        public string Codigo_Radio { get; set; }
        public string Tarjeta_Maestra { get; set; }
    
        public virtual usuarios usuarios { get; set; }
    }
}
