//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acotma_API.Models_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class asignacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public asignacion()
        {
            this.verificacionSalida = new HashSet<verificacionSalida>();
        }
    
        public int idAsignacion { get; set; }
        public string tipoUnidad { get; set; }
        public Nullable<int> economico { get; set; }
        public Nullable<int> tarjeton { get; set; }
        public string nomChofer { get; set; }
        public Nullable<int> fkCorrida { get; set; }
        public Nullable<System.DateTime> fkFecha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<verificacionSalida> verificacionSalida { get; set; }
        public virtual horarioServicio horarioServicio { get; set; }
    }
}
