//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acotma_API.Models_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class asignacion
    {
        public int idAsignacion { get; set; }
        public string tipoUnidad { get; set; }
        public Nullable<int> economico { get; set; }
        public Nullable<int> tarjeton { get; set; }
        public string nomChofer { get; set; }
        public Nullable<int> fkVerificacionSalida { get; set; }
        public Nullable<int> fkCorrida { get; set; }
        public Nullable<System.DateTime> fkFecha { get; set; }
    
        public virtual horarioServicio horarioServicio { get; set; }
        public virtual verificacionSalida verificacionSalida { get; set; }
    }
}
