//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acotma_API.Models_DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ACOTMADBEntities : DbContext
    {
        public ACOTMADBEntities()
            : base("name=ACOTMADBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<asignacion> asignacion { get; set; }
        public virtual DbSet<estado> estado { get; set; }
        public virtual DbSet<horarioServicio> horarioServicio { get; set; }
        public virtual DbSet<permisos> permisos { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<verificacionDia> verificacionDia { get; set; }
        public virtual DbSet<verificacionSalida> verificacionSalida { get; set; }
    }
}
