//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acotma_API.Models_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Informe_incidencias_tecnologicas
    {
        public int ID_InformeIncidencias { get; set; }
        public System.DateTime Fecha_incidencia { get; set; }
        public Nullable<System.TimeSpan> Hora_de_registro { get; set; }
        public string Servicio { get; set; }
        public string VehiculoECO { get; set; }
        public string Equipo_afectado { get; set; }
        public string Falla { get; set; }
        public string usuario { get; set; }
    
        public virtual usuarios usuarios { get; set; }
    }
}
