//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acotma_API.Models_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Informe_Limpieza
    {
        public int IdInformeLimpieza { get; set; }
        public System.DateTime Fecha_Limpieza { get; set; }
        public string Estación { get; set; }
        public string LimpiezaPiso { get; set; }
        public string LimpiezaVidrio { get; set; }
        public string LimpiezaAreaServicios { get; set; }
        public string LimpiezaAreaEstructura { get; set; }
        public string LimpiezaTorniquetes { get; set; }
        public string LimpiezaSanitarios { get; set; }
        public string Observaciones { get; set; }
        public string Usuario { get; set; }
    
        public virtual usuarios usuarios { get; set; }
    }
}
