//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acotma_API.Models_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class permisoUsuario
    {
        public int idPermisoUsuario { get; set; }
        public string usuario { get; set; }
        public string permiso { get; set; }
    
        public virtual permisos permisos { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
