//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acotma_API.Models_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro_Vehicular
    {
        public int Id_RegistroVeh { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Nombre_solicitante { get; set; }
        public string Marca_vehiculo { get; set; }
        public string Submarca { get; set; }
        public string Placa { get; set; }
        public string Tiempo { get; set; }
        public string Area_solicitante { get; set; }
        public string Actividades_a_realizar { get; set; }
        public string Registro_de_kilometraje { get; set; }
    }
}
