//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acotma_API.Models_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class verificacionDia
    {
        public int idVerificacionDia { get; set; }
        public Nullable<int> noUnidad { get; set; }
        public string observaciones { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string fkUsuario { get; set; }
        public Nullable<int> fkEstado { get; set; }
    
        public virtual estado estado { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
