//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acotma_API.Models_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class verificacionSalida
    {
        public int idVerificacionSalida { get; set; }
        public string estado { get; set; }
        public string observaciones { get; set; }
        public Nullable<System.TimeSpan> horaSalida { get; set; }
        public string fkusuario { get; set; }
        public Nullable<int> fkasignacion { get; set; }
    
        public virtual asignacion asignacion { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
